### ISSUE TITLE
No file show

### ISSUE THREAD

**Issue by VoXaN24** [ArnabXD/Dropbox-Index#1]
I have follow the guide but i don't have any file show :c 
![image](https://user-images.githubusercontent.com/30030208/149357470-a035fd2e-9537-438e-918a-c19c65bbc5da.png)

**Comment by ArnabXD** [comment]
With this much details I can't debug it accurately 😅 . 

Can you share the response for this ?

your-website.domain/api/explore

(e.g: https://dropx.arnabxd.me/api/explore)

**Comment by VoXaN24** [comment]
That weird it's ok but it don't view the autorization
![image](https://user-images.githubusercontent.com/30030208/149366701-c7e1a41e-8b6c-4bae-b36a-797d264b59a1.png)

**Comment by ArnabXD** [comment]
Can you try regenerating a new token (for same app). If you update permissions then you need to create another token for those permissions

**Comment by VoXaN24** [comment]
I have generate a new token, set it, and rebuild the vercel app, i say to you if it's resolve the issue

**Comment by VoXaN24** [comment]
It's ok now ! 👍🏽 
I closed it and thank's for the help !
