### ISSUE TITLE
Dropbox "No Expiration Token" 

### ISSUE THREAD

**Issue by newd2459** [ArnabXD/Dropbox-Index#103]
hi , pls try again i talked to dropbox support today and they just replied that long -lived tokens are not available anymore, from sept 2021 they have started the update and only short lived tokens will be given , to automate the process of obtaining new token we can get a refresh token and using api we can get new short lived token. These are the links they provided -
https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type
https://www.dropbox.com/developers/documentation/http/documentation#authorization
https://developers.dropbox.com/oauth-guide

**Comment by newd2459** [comment]
hi , pls try again i talked to dropbox support today and they just replied that long -lived tokens are not available anymore, from sept 2021 they have started the update and only short lived tokens will be given , to automate the process of obtaining new token we can get a refresh token and using api we can get new short lived token. These are the links they provided -
https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type
https://www.dropbox.com/developers/documentation/http/documentation#authorization
https://developers.dropbox.com/oauth-guide

**Comment by ArnabXD** [comment]
Thank you very much for your investigation. I wasn't aware of this as my token was working fine and no one made a detailed issue. I will try to update DropBox-Index in the upcoming weekend.

**Comment by newd2459** [comment]
currently i am using this to get new sl tokens 
https://stackoverflow.com/questions/70641660/how-do-you-get-and-use-a-refresh-token-for-the-dropbox-api-python-3-x
maybe this will help a little

**Comment by ArnabXD** [comment]
I have implemented the refresh token generation. I will be writing proper documentation but before that, I would like you to test this out.


Now `.env.local` file has requirement changes. You can clone again or simply run `git pull` inside the previously cloned directory to update. You can check the `.env.sample` file as an example

- Go to the DropBox app console and collect the client id and secret. Fill them in `.env.local` file. (`APP_ID` should have the client id and `APP_SECRET` should be the client secret)
- Add a redirect URL to your Dropbox app. As you were running in port 10000 your redirect URL should be `http://localhost:10000/api/auth/token`. If you were using vercel or any other provider you can replace the host (localhost:10000) accordingly.
- Now visit `http://localhost:10000/api/auth` in your browser and you will be asked for authorization (do it even though it might say unsafe, It is your own client after all).
- You will get a JSON response that includes a refresh token. set that as `REFRESH_TOKEN` in `.env.local` and restart the app.

Now your site should be working.


Additionally, disallow public clients (optional).

![image](https://user-images.githubusercontent.com/52126165/178115060-d1463689-3ed9-4b0e-a7af-34100a0a4a94.png)

**Comment by pandamoon21** [comment]
> currently i am using this to get new sl tokens https://stackoverflow.com/questions/70641660/how-do-you-get-and-use-a-refresh-token-for-the-dropbox-api-python-3-x maybe this will help a little

This support page is helpful too if anyone need it
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Get-refresh-token-from-access-token/td-p/596739
