### ISSUE TITLE
[Enchantement] Add the size of the File

### ISSUE THREAD

**Issue by VoXaN24** [ArnabXD/Dropbox-Index#2]
According to the DropBox API Documentation
It's possible to add the FileSize into showed information 
[https://www.dropbox.com/developers/documentation/http/documentation#files-export](https://www.dropbox.com/developers/documentation/http/documentation#files-export)

I try to look where i need to add it but don't realy understant the code :/

**Comment by ArnabXD** [comment]
Hello @VoXaN24 . Thank you for the feature request. I will add the size property. But for screens > md. What do you think about it. [ListFolder](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) already returns size property to files.

**Comment by VoXaN24** [comment]
Don't show it for a small screen is a good thing yes !

**Comment by ArnabXD** [comment]
Well  , It is live 😄 .

**Comment by VoXaN24** [comment]
Btw another thing, when we click in the file name, it redirict into the download link like the download bouton can be a good thing ? Like when you navigate into an opendirectory

**Comment by ArnabXD** [comment]
Yes , why not.

**Comment by VoXaN24** [comment]
Another sudgestion, show the content of readme.md file.
[https://stackoverflow.com/questions/6110953/how-to-print-out-a-markdown-file-on-the-console-using-node-js](https://stackoverflow.com/questions/6110953/how-to-print-out-a-markdown-file-on-the-console-using-node-js)
 idk if the link can help you

**Comment by ArnabXD** [comment]
It will be added, soon.
